### PR TITLE
Allow truncated data

### PR DESCRIPTION
**Pull request by andlaus**
this is useful in [some situations](https://github.com/cantools/cantools/issues/407).

Andreas Lauser &lt;<andreas.lauser@mercedes-benz.com>&gt;, on behalf of [MBition GmbH](https://mbition.io/).
[Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

### CODE REVIEW

**Comment by eerimoq** [comment]
Hi,

I partially read the cantools issue, but wouldn't it be possible to append `0xff...` to the received frame data to make it the required length?

**Comment by andlaus** [comment]
BTW: I noticed that compared to `bitstruct`, `bitstruct.c` has quite a few more ommisions than I anticipated:

 - its methods only accept `bytes` objects, not `bytearray`
 - there is no `Error` class that gets raised when something goes wrong
 - the error messages of exceptions are quite different from the ones of `bitstruct`

I also think that cantools requires bit and byte order support (correct me if I'm wrong), so most likely I'll come back with a few  follow up PRs in the near future. (The -- somewhat ambitious -- goal here  is to make `test_bitstruct.py` work with `bitstruct.c`.)

**Comment by andlaus** [comment]
>  the problem with that is that it is impossible to know which signals contain real data and which contain only garbage.

also, this might make some signals go out of their valid range, i.e., `Message.decode()` would choke in that case...

**Comment by andlaus** [comment]
hm, segmentation fault on some versions. I suppose I'll have to fire up valgrind tomorrow...

**Comment by andlaus** [comment]
> I see. Sounds fair. I think this PR is ok, but have to think about it for a day or two.

no worries. I'll probably need at least as long to bring it up to snuff anyway ;)

**Comment by andlaus** [comment]
okay, I hope the segfaults are gone now. (I forgot to zero-initialize the `allow_truncated_p` variable at one place. On my machine `valgrind` no longer indicates any warnings stemming from `c.c`.)

**Comment by eerimoq** [comment]
Looks good to me. Anything else you are about to change or should I merge?

**Comment by andlaus** [comment]
cool, thanks. I think this is ready. That said, I'd like to give you a heads up that I'll probably open a few more PRs in the near to medium term future with the goal of making the python and C implementations equivalent w.r.t. features...

**Comment by eerimoq** [comment]
sounds good

**Pull request merged**
