### PR TITLE
Added power support 

### PR DESCRIPTION
**Pull request by dthadi3**
Thanks for your code, Its working good.

Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.

### CODE REVIEW

**Comment by eerimoq** [comment]
@gerrith3 Please give a detailed explanation why this is needed. Thanks.

**Comment by gerrith3** [comment]
@eerimoq apologies I missed the notification on this one.  We are working to make sure packages that are part of Debian/Ubuntu's ppc64le distributions are built regularly upstream on power, instead of waiting to test at the end of/after a release.  The reduces the cost/effort of keeping these packages in the debian/ubuntu distros.  This is part of the work where IBM is moving hardware around, including free hardware now in the Travis CI build space.  Making this change ensures that the package regularly builds on the Power architecture and will point out any issues as soon as they happen.

**Comment by eerimoq** [comment]
I prefer as few Travis jobs as possible as they take time to execute and they are run on every commit. Maybe build tagged releases for more architectures, but I dunno... what when another architecture is added, and another, and so on. Sounds like a lot of overhead to test for all of them (with only a small gain).

**Comment by gerrith3** [comment]
Building only specifically tagged releases is a generally good idea, although the point of travis is that machine time is relatively free as compared to human time.  Having debian or ubuntu, fedora/RHEL people coming through to find a regression is a lot of overhead on someone else when it could have been caught by an automated CI.  Travis CI is free to you and the Power servers that we provide are exactly for doing these regression tests.  Otherwise getting 70,000 projects to build with a few random failures is a real PITA.

**Pull request closed without merging**
